version: "3.8"
services:
  mysqldb:
    image: mysql:8
    #   command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fuel_api
      - MYSQL_HOST=0.0.0.0
      - MYSQL_TCP_PORT=3306
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
